name: Check Resource Links
on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes for testing
  branches:
    - cron-job 
jobs: 
  check-validation:
    name: Check resource links and create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install frontend dependencies
        uses: bahmutov/npm-install@v1
      - name: Check resource links
        uses: ./.github/actions/resource-links
      - name: Commit files and create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Get updated resource files
          committer: William Hutt <whutt1994@gmail.com>
          author: William Hutt <whutt1994@gmail.com>
          branch: action/updated-resource-files
          base: cron-job
          title: 'Update resource json files(s) to remove invalid resources'
          body: |
            The resource files have been updated with the latest valid resources.
            *This PR was auto-generated.*